# Generated by Django 2.1.1 on 2018-09-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clickmon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hp_max', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('element', models.CharField(max_length=20)),
                ('img_front', models.ImageField(upload_to='')),
                ('img_back', models.ImageField(upload_to='')),
                ('stamina', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mdp', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Mr', 'Garçon'), ('Mme', 'Fille')], default='Mr', max_length=20)),
                ('money', models.IntegerField(default=50)),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='clickmon',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickmon', to='dualMonster.Summoner'),
        ),
    ]
