# Generated by Django 2.1.1 on 2018-09-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dualMonster', '0003_auto_20180906_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attack',
            name='img',
            field=models.ImageField(max_length=10, upload_to=''),
        ),
        migrations.AlterField(
            model_name='attack',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='attackpack',
            name='Clickmon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickmon_attack', to='dualMonster.Clickmon'),
        ),
        migrations.AlterField(
            model_name='attackpack',
            name='attack_four',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_four_rn', to='dualMonster.Attack'),
        ),
        migrations.AlterField(
            model_name='attackpack',
            name='attack_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_one_rn', to='dualMonster.Attack'),
        ),
        migrations.AlterField(
            model_name='attackpack',
            name='attack_three',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_three_rn', to='dualMonster.Attack'),
        ),
        migrations.AlterField(
            model_name='attackpack',
            name='attack_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_two_rn', to='dualMonster.Attack'),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='element',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='hp_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='img_back',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='img_front',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='stamina_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickmon', to='dualMonster.Summoner'),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='gender',
            field=models.CharField(choices=[('Mr', 'Garçon'), ('Mme', 'Fille')], default='Mr', max_length=20),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='mdp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='money',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
