# Generated by Django 2.1.1 on 2018-09-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualMonster', '0004_auto_20180906_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='element',
            field=models.CharField(default='lol', max_length=20),
            preserve_default=False,
        ),
    ]
