# Generated by Django 2.1.1 on 2018-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualMonster', '0005_attack_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
