# Generated by Django 2.1.1 on 2018-09-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dualMonster', '0006_auto_20180906_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='stamina_cost',
            field=models.IntegerField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
