# Generated by Django 2.1.1 on 2018-09-06 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dualMonster', '0010_auto_20180906_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickmon',
            name='hp',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='stamina',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='clickmon',
            name='summoner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clickmons', to='dualMonster.Summoner'),
            preserve_default=False,
        ),
    ]
